### ISSUE TITLE
Replying doesn't ping Discord users anymore

### ISSUE THREAD

**Issue by Fabian42** [TediCross/TediCross#100]
Since replies were changed to some kind of embedded message, the replied-to user doesn't get pinged anymore. If they have the chat muted, that means that they don't get notified of the reply.

This (not pinging) is not only unintuitive and usually not wanted, but also different than how Telegram replies inside Telegram work, they always ping and use the appriopriate notification sound.

**Comment by Suppen** [comment]
Could you please elaborate? My tests show that the replied-to user is pinged. I also get a notification for it
![bilde](https://user-images.githubusercontent.com/12338293/55817783-849ed580-5af5-11e9-8802-ccc563902a33.png)

**Comment by Fabian42** [comment]
There's not much to say, someone just told me that it didn't ping them and
sent me a screenshot. I'm attaching a screenshot of the relevant chat
excerpt. Shouldn't Discord highlight the entire message when you're pinged?

**Comment by Fabian42** [comment]
![Screenshot_20190408-011725_Telegram](https://user-images.githubusercontent.com/10481506/55823842-eb76bb80-5b02-11e9-8782-eb9742a90b1f.png)

**Comment by Fabian42** [comment]
![Screenshot_20190409-200727_Telegram](https://user-images.githubusercontent.com/10481506/55823959-27118580-5b03-11e9-8fc5-9e219c363bc7.png)

**Comment by Suppen** [comment]
Fixed in version 0.8.4, but please go directly to 0.8.5, which was released at the same time

**Comment by trgwii** [comment]
(Please use latest version, as it fixes some critical bugs present in 0.8.5!)
