### ISSUE TITLE
Feature suggestion: Restore old reply behaviour

### ISSUE THREAD

**Issue by Fabian42** [TediCross/TediCross#103]
I was just notified by people on Discord that the Telegram replies look much different now on the Discord end than they used to: They no longer ping the replied-to user (#100), they take up more space and they seem to be cut off after more text, thereby repeating more of what was already said.

I liked the old reply functionality of just having one line with "Name (in reply to @user: \"blablablablabla…\")", that contained all the needed information in a very compact way. Can this please be restored?

**Comment by Suppen** [comment]
There is an issue on https://github.com/discordjs/discord.js/issues/1519 saying mentions in embeds do not work (#100). It may or may not be the case, but I may have found a solution everyone can be happy with. I'm moving the `Reply to @user` out of the embed and into the main text, so the mention definitely works. The replied-to message still stays in the embed
![bilde](https://user-images.githubusercontent.com/12338293/55827645-f33a5e00-5b0a-11e9-9c65-dca81adf353c.png)

In addition to this, maybe I will add a global setting for how many characters the replied-to message will contain. At the moment it is up to 100.

Could this be a satisfactory solution?

**Comment by Fabian42** [comment]
It's still bigger than before, but that would get back all the features. I don't really understand why embeds are used at all.

**Comment by Suppen** [comment]
When it was just pure text, it was hard to separate between the replied-to text and the reply. I tried fixing that with a few spaces at the start of the replied-to text, but still not very clear
![bilde](https://user-images.githubusercontent.com/12338293/55831887-8330d580-5b14-11e9-8b3a-8ba269805f8f.png)

**Comment by Suppen** [comment]
The change is now pushed to the development branch (commit 6a08ab7d3bf7b1b96ae259050c2b11f2fa9b57e5). I have not yet added the reply-length settings, and I won't be able to make a release before thursday

**Comment by Fabian42** [comment]
That could be solved by making it look like this:

*Suppen* (in reply to @Supp3n: "*The cake is a…*")
And the cube had to die for it.

**Comment by Suppen** [comment]
I made it an option. There is now a setting `discord.displayTelegramReplies` (not per bridge) which can be set to either `inline` or `embed`. Along with a setting `discord.replyLength` (also not per bridge) which decides how many characters of the original text are shown
This is all part of version 0.8.4, but please use version 0.8.5 instead

**Comment by trgwii** [comment]
(Please use latest version, as it fixes some critical bugs present in 0.8.5!)
