### ISSUE TITLE
Telegram Channel's support

### ISSUE THREAD

**Issue by rosivanov** [TediCross/TediCross#110]
Hi! According to steps 8 and 11 [(Installation)](https://github.com/TediCross/TediCross#step-by-step-installation) the bot needs to be an admin to let it read messages in telegram Channel. And there is no way to do it without admin permissions. Am i right?

**Comment by Suppen** [comment]
I'm not sure it needs to be full admin anymore, but i needs elevated permissions. You cannot get TediCross to function without either being or knowing the admin of the Telegram groups/channels you want to use it in

**Comment by rosivanov** [comment]
Yes, a bot needs to be an admin.
