### ISSUE TITLE
Reply indicator T->D disappears when editing message

### ISSUE THREAD

**Issue by Fabian42** [TediCross/TediCross#115]
I'm using the "old" style reply indicator. When I reply to a message, that person gets properly pinged and the reply preview is added, but when I edit my message, that line disappears completely. This also creates a "ghost ping" on Discord, because apparently Discord is bad at removing the indicator.

**Comment by Suppen** [comment]
A fix for this (and many other things; it has been an architectural problem) has been in the works for a few weeks. The latest commit on the development branch (b1bfe82e46419b8f5b10569443885fddc980d7b0) should fix it. [Try it out if you wish](https://github.com/TediCross/TediCross/tree/b1bfe82e46419b8f5b10569443885fddc980d7b0). It may still be a few days before it is released, as I need to proof read and test the code

**Comment by Suppen** [comment]
This should be fixed now in version 0.9.0
