### ISSUE TITLE
Telegram Spam

### ISSUE THREAD

**Issue by travis1234** [TediCross/TediCross#117]
Is there a way to stop spam like this?

![Screenshot_2019-07-30-22-04-48-328_com discord](https://user-images.githubusercontent.com/4219774/62178231-a31e2a80-b38b-11e9-8c8c-f0c1fc62c90b.jpg)

**Comment by Suppen** [comment]
I assume you have a moderator bot in Telegram which deletes this message there, but TediCross relays it anyway.

Unfortunately this is not possible to fix, as Telegram has decided bots cannot detect when a message is deleted. See issue #78
