### ISSUE TITLE
Sync Username and Avatar

### ISSUE THREAD

**Issue by greerso** [TediCross/TediCross#122]
Rather than using the bot name and avatar with username in message body, pass through discord/telegram username and avatar.

**Comment by Suppen** [comment]
We have tried implementing this on Discord, using Discord's webhook system. It worked, and looked very nice, but it also had some serious drawbacks. The biggest being that messages delivered by webhooks cannot be edited. The bot has no control over them after they are sent. It also requires the bot owner to have 2 factor authentication activated, which may be a hassle for them.

A pair of other Discord bot developers tried, independently of me, but at the same time, to implement these webhooks. They reached the same conclusion, and found the way it works now to be functionally better.

There is no way to do this on the Telegram side. The bot can only have one set of name and avatar, and both are chosen by the bot owner. They cannot be programmatically changed.

**Comment by vico93** [comment]
I wish there were an option to enable it, at expense of the message deleting sync, in the bot. In my case (a very private server and group), deleting would not be an issue, i think.
