### ISSUE TITLE
suddenly getting  UnhandledPromiseRejectionWarning error

### ISSUE THREAD

**Issue by open4profit** [TediCross/TediCross#123]
Till morning it was working perfectly fine, but suddenly it stopped and giving below error - Let me know how to solve this issue.
error code 
(node:14932) UnhandledPromiseRejectionWarning: Error: 404: Not Found
    at buildConfig.then.then.then.then (E:\Downloads\TediCross\node_modules\telegraf\core\network\client.js:263:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Suppen** [comment]
This looks like a connectivity issue. Can you check that you can access https://api.telegram.org from the server running TediCross?

**Comment by Suppen** [comment]
Closing due to lack of info, and probably it was a network issue
