### ISSUE TITLE
Mentioning a user on the other platform

### ISSUE THREAD

**Issue by oxr463** [TediCross/TediCross#128]
If a user in Telegram mentions a Discord user, or vice versa; then when trying to select that user, it says the user does not exist. This is true, since the user only exists on the other platform; however, would it be possible to link to the user's account anyway?

Example:

@alice lives on Telegram.

@bob lives on Discord.

@alice mentions @bob in her message on Telegram.

Clicking the user's name in Telegram web returns the following error:

># Not found
>There is no Telegram account with the username you provided. 
>```
>Method: contacts.resolveUsername
>Result: {"_":"rpc_error","error_code":400,"error_message":"USERNAME_NOT_OCCUPIED"}
>```

**Comment by bob** [comment]
@oxr463 mentions @bob on Github
Oh, hi Lucas!

**Comment by Suppen** [comment]
Although I'm not entirely sure what you are asking, I can fairly certainly say: No, this is not possible.

The Telegram bot doesn't have a clue which users exist and which does not. When you write "@someone" in Telegram, the bot gets the string, along with a list of so-called entities, saying that "@someone" is a username. The bot has no way of knowing if that user exists or not. It just knows it is a valid username, but not if anyone has it.
Also, the Telegram bot doesn't send any special markup for users. It sends "@someone" in plaintext, and the Telegram client itself decides that is a username and makes it clickable.

The Discord bot knows a bit more. It knows which users are in the server, but which users are not in the server. The messages, both those sent and received my the bot, has special markdown telling that this is a user. This also means Discord itself will handle existing and non-existing users:
![bilde](https://user-images.githubusercontent.com/12338293/73127451-b4ee2c80-3fc0-11ea-8773-f7c6cf497096.png)

Hope this answers your question
