### ISSUE TITLE
DiscordAPIError: Missing Permissions

### ISSUE THREAD

**Issue by oneassasin** [TediCross/TediCross#140]
I add to discord server bot with 248832 permissions from link in README, but repost by t2d scheme throw a error 
How to fix it?

**Comment by Suppen** [comment]
In some cases it may be necessary to also set the permissions on the individual channels. Look under "Permissions" in the channel settings. The bot must be allowed to:
- Read messages
- Send messages
- Manage messages
- Embed Links
- Attach files
- Read message history

**Comment by oneassasin** [comment]
three hours after... closed issue, bot doesn't have permissions on channel :D
