### ISSUE TITLE
Update to discord.js v12 before November 7

### ISSUE THREAD

**Issue by teejo75** [TediCross/TediCross#142]
Discord are moving their api from discordapp.com to discord.com (Discord bot owners should have received an email or discord message detailing the information).

According to [this issue on discord.js](https://github.com/discordjs/discord.js/pull/4160#issuecomment-660130599), they have updated v12 to reflect the change, but will not be updating v11.

There apparently hasn't yet been an npm release of discord.js v12 that incorporates this change.

**Comment by Suppen** [comment]
Version 0.10.0 and higher of TediCross has updated the discord library, and now uses discord.com instead of discordapp.com
