### ISSUE TITLE
"This is an instance of a TediCross bot, bridging a chat in Telegram with one in Discord." spamming other channels in the server

### ISSUE THREAD

**Issue by vico93** [TediCross/TediCross#144]
_Followup of #143, i created a new ticked because now i'm running just one instance._

Well, i've updated to 0.10.1 (latest commit from now), and now this nagging message is shown in any other non-bridged discord channel, even with the bridges themselves are being synced correctly.

[Here](https://hastebin.com/ifiticoxos.bash) is my settings.yaml (i've redacted just the tokens/channels/groups strings/numerics, and keep the apostrophes/hyphens used for reference.

**Comment by Suppen** [comment]
Apparently a blunder snuck into v0.10.0 (and 0.10.1): TediCross sends the "This is an instance of TediCross..." message to non-bridged channels on a server with bridges.

This has been fixed in v0.10.2

**Comment by vico93** [comment]
thanks, will update!
