### ISSUE TITLE
Any contact information?

### ISSUE THREAD

**Issue by jagzmz** [TediCross/TediCross#145]
Hi Suppen,
Loved your code, I know this issue isn't related to this project, I just could not find your contact email, or any IM information, I would love to talk about the code, and some other questions about the project. Could you provide any IM? or could you ping mine..... Discord: **`killswitc_h#0496`** . Hoping you will see this.

Thanks

**Comment by Suppen** [comment]
Hello. It is not difficult to find me on Telegram or Discord, as there are links to TediCross' support groups there in this repo. I will, however, not answer direct messages.
If you have questions about TediCross, please ask in the support groups
If you have questions about JavaScript, please find a JavaScript related group on Discord or Telegram
If you want to talk about anything else, including job offers and the like, I'm not interested, and your requests will be ignored
