### ISSUE TITLE
D→T pings no longer work

### ISSUE THREAD

**Issue by Fabian42** [TediCross/TediCross#148]
Pings on Discord now have a space after the @ on Telegram for some reason. This breaks all pings.

**Comment by Suppen** [comment]
After some thorough debugging, we have discovered it isn't really a space, but a zero-width-space (charcode 8203). Telegram converts it to an ordinary space.
It comes from Discord itself, meaning it is not added by TediCross.
It is somehow localized to @Fabian42's setup. I have a test settings file which works as expected on my machine, but when using that very same settings file on Fabian's machine, the space was there.

This is not an issue with TediCross, but with Discord.
