### ISSUE TITLE
Multiple channels / groups

### ISSUE THREAD

**Issue by mentalisit** [TediCross/TediCross#151]
Good day.  Is it possible to configure multiple telegram chats in one bridge?

**Comment by Suppen** [comment]
No, but you can make multiple bridges with different Telegram chats and the same Discord channel

**Comment by mentalisit** [comment]
messages from different telegram channels go to the Discord room.  but how to get them to come in telegrams too

**Comment by Suppen** [comment]
You want a Telegram <-> Telegram bridge? That is not possible with TediCross

**Comment by mentalisit** [comment]
I need to connect 5 Telegram channels and 8 Discord rooms

**Comment by mentalisit** [comment]
in contention it's easy ... but bots are not forwarded to Tedicross

**Comment by Suppen** [comment]
Please describe exactly what you want

**Comment by mentalisit** [comment]
how to allow sending messages from bots through tedicross

**Comment by Suppen** [comment]
Does this answer your question?
https://github.com/TediCross/TediCross#the-telegram-bot-doesnt-relay-messages-sent-by-other-bots

**Comment by mentalisit** [comment]
I need not in a telegram, but in a discord

**Comment by Suppen** [comment]
I do not understand what your question is. Please follow this guide on how to ask good questions:
https://stackoverflow.com/help/how-to-ask

**Comment by mentalisit** [comment]
you need all messages in Discord including messages from bots.  need to be sent in telegram

**Comment by Suppen** [comment]
That is how TediCross works by default. It is, however, not what this issue is about. Please open a new issue if you still have problems with it.
Has the original question been answered?
