### ISSUE TITLE
User filtering

### ISSUE THREAD

**Issue by pdemaio** [TediCross/TediCross#152]
Is there any way to forward messages from a particular user (or list of users) from telegram to discord? If there's nothing out of the box, any idea where to look for implementing that filter?

**Comment by Suppen** [comment]
No, this is not possible. I would recommend creating a group or channel where only the ones you want to forward from is.

TediCross is free and open source, so you are free to do with is as you please, including modifying the code to suit your needs. Modifying the code is, however, not supported. You are free to do it, but you won't get help.
