### ISSUE TITLE
Message edits always error and fail to relay

### ISSUE THREAD

**Issue by Govindass** [TediCross/TediCross#154]
I am getting error like this every time a message is edited:
```
2020-10-04 11:37:01 [ERR] [Chat Relay] Could not edit Telegram message: TelegramError: 400: Bad Request: message to edit not found
    at /servers/TediCross-master/node_modules/telegraf/core/network/client.js:281:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /servers/TediCross-master/src/discord2telegram/setup.js:283:5 {
  code: 400,
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: message to edit not found'
  },
  description: 'Bad Request: message to edit not found',
  parameters: {},
  on: {
    method: 'editMessageText',
    payload: {
      text: '<b>Govindas</b>\n' +
        "message text",
      chat_id: redacted,
      parse_mode: 'HTML'
    }
  }
}
```

**Comment by Suppen** [comment]
Is the edit relayed?

**Comment by Govindass** [comment]
> 
> 
> Is the edit relayed?

the edit is never visible on the other side

**Comment by Suppen** [comment]
Which TediCross version are you running? You can see it near the top in the `package.json` file

**Comment by Govindass** [comment]
> 
> 
> Which TediCross version are you running? You can see it near the top in the `package.json` file

0.10.4

**Comment by Suppen** [comment]
TediCross keeps track of which messages on Discord/Telegram corresponds to which messages on Telegram/Discord in memory. The mappings are deleted 24 hours after they are made.
In practice, this means that edits will fail if the message is older than 24 hours, or if the message was sent before the bot was started.
Could this be the cause of your error?

**Comment by Govindass** [comment]
> 
> 
> TediCross keeps track of which messages on Discord/Telegram corresponds to which messages on Telegram/Discord in memory. The mappings are deleted 24 hours after they are made.
> In practice, this means that edits will fail if the message is older than 24 hours, or if the message was sent before the bot was started.
> Could this be the cause of your error?

the message has been edited 1 minute after it was sent, additionally the message was relayed between the two, meaning the bot was online, just the edit is not being relayed

**Comment by Suppen** [comment]
Which node version are you running? `node -v`

**Comment by Govindass** [comment]
> 
> 
> Which node version are you running? `node -v`

v12.18.4

**Comment by Suppen** [comment]
You are running the latest version of TediCross, and using a supported node version.
Are there any other errors in the console? Any specific types of messages which fails on editing?

**Comment by Govindass** [comment]
> You are running the latest version of TediCross, and using a supported node version.
> Are there any other errors in the console? Any specific types of messages which fails on editing?

my error is included in the first post

**Comment by Govindass** [comment]
it unexpectedly started working, I guess I'll close this issue for now

**Comment by Suppen** [comment]
Errors which fix themselves are the best. I have no idea what the cause was, as nobody else reported it, and my tests couldn't reproduce it, but it suddenly disappearing might indicate it was a problem at Telegram's end
