### ISSUE TITLE
bot just dies

### ISSUE THREAD

**Issue by unimatrix999** [TediCross/TediCross#158]
/home/tgbot/src/discord2telegram/setup.js:43
                        .map(({ id }) => bridgeMap.fromDiscordChannelId(id))
                         ^

TypeError: member.guild.channels.map is not a function
    at Client.<anonymous> (/home/tgbot/src/discord2telegram/setup.js:43:5)
    at Client.emit (events.js:315:20)
    at Object.module.exports [as GUILD_MEMBER_ADD] (/home/tgbot/node_modules/discord.js/src/client/websocket/handlers/GUILD_MEMBER_ADD.js:16:14)
    at WebSocketManager.handlePacket (/home/tgbot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/tgbot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/tgbot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/tgbot/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/home/tgbot/node_modules/ws/lib/websocket.js:797:20)
    at Receiver.emit (events.js:315:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tedicross@0.10.3 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tedicross@0.10.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-11T05_15_33_588Z-debug.log
You have new mail in /var/spool/mail/root
[root@chaozhq tgbot]# npm start

**Comment by Suppen** [comment]
You have a wrong channel ID in your settings. Verify them, and make sure they are wrapped in single quotes

**Comment by unimatrix999** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.8
3 info using node@v12.18.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle tedicross@0.10.3~prestart: tedicross@0.10.3
6 info lifecycle tedicross@0.10.3~start: tedicross@0.10.3
7 verbose lifecycle tedicross@0.10.3~start: unsafe-perm in lifecycle true
8 verbose lifecycle tedicross@0.10.3~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/tgbot/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle tedicross@0.10.3~start: CWD: /home/tgbot
10 silly lifecycle tedicross@0.10.3~start: Args: [ '-c', 'node main.js' ]
11 silly lifecycle tedicross@0.10.3~start: Returned: code: 1  signal: null
12 info lifecycle tedicross@0.10.3~start: Failed to exec start script
13 verbose stack Error: tedicross@0.10.3 start: `node main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid tedicross@0.10.3
15 verbose cwd /home/tgbot
16 verbose Linux 3.10.0-1127.18.2.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.18.3
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error tedicross@0.10.3 start: `node main.js`
22 error Exit status 1
23 error Failed at the tedicross@0.10.3 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by unimatrix999** [comment]
- name: ia.public
    direction: both
    telegram:
      chatId: '-1001401102861'
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: true
      relayCommands: true
      crossDeleteOnDiscord: true
    discord:
      channelId: '685608177365942292'
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: true
      crossDeleteOnTelegram: true
  - name: xvx.private
    direction: both
    telegram:
      chatId: '-1001448323081'
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: true
      relayCommands: true
      crossDeleteOnDiscord: true
    discord:
      channelId: '730835537484578836'
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: true
      crossDeleteOnTelegram: true

**Comment by unimatrix999** [comment]
2020-10-11 23:52:14 [INFO] Telegram: IArelaybot (911927997)
2020-10-11 23:52:14 [INFO] Discord: ChaozRelay (356130274053980162)
 no mention of wrong channel id in console

**Comment by Suppen** [comment]
It doesn't mention it before trying to use it. It then mentions it by giving the above error message. Please run the /chatinfo command in all bridged Discord channels, and make sure you have copied them correctly

**Comment by unimatrix999** [comment]
no offense suppen but the relay works fine on both discord channels & telegram , if the channel id was wrong it wouldnt work , the bot just suddently dies

**Comment by Suppen** [comment]
I see. You are using TediCross v0.10.3, which had this bug when someone joins a Discord server. Please upgrade to TediCross 0.10.4, where this is fixed

**Comment by unimatrix999** [comment]
done lets see if it re-occurs now
