### ISSUE TITLE
Telegram not forwarding messages to discord unless implicitly sent through the telegram interface

### ISSUE THREAD

**Issue by CryptoKnightsGit** [TediCross/TediCross#180]
I have created a scraping script to send messages using the same bot added to the bridge. The scraper works and sends the message in the chat but the message does not get bridged to discord. If I send a manual message in the chat it gets bridged. Is there any fix for this?

Thanks again for the great tool you have created!

**Comment by Suppen** [comment]
Is your scraper a bot? In which case, this applies: https://github.com/TediCross/TediCross#the-telegram-bot-doesnt-relay-messages-sent-by-other-bots

**Comment by CryptoKnightsGit** [comment]
Well my scraper bot uses the same exact bot ID used in TediCross. Does that issue still apply?

**Comment by Suppen** [comment]
Do not use one bot for multiple applications. That will cause all sorts of weird problems

**Comment by CryptoKnightsGit** [comment]
Gotcha! 😊 It's working perfectly fine, for now haha Would you be able to help me integrate the scraper within TediCross? I am having a lot of trouble figuring out how to run it within my scraper script 😔

**Comment by Suppen** [comment]
TediCross is free and open source, meaning you can do whatever you want with it. Code changes are, however, unsupported. You are free to make them, but you are on your own.
