### ISSUE TITLE
Auto-reply to PMs

### ISSUE THREAD

**Issue by Fabian42** [TediCross/TediCross#182]
Often people try to PM my TediCross bot on Discord, which goes nowhere, but also doesn't tell them that it doesn't work. It would be good if the bot had some kind of auto-reply for that case.
Maybe it would also be good on Telegram, but there it's a bit more apparent anyway, because you need to click "start" or enter "/start".

**Comment by Suppen** [comment]
The bot does have auto-reply to PMs, as it does with any non-bridged chat. Doesn't it work for you?
![image](https://user-images.githubusercontent.com/12338293/111027664-f07ccd80-83f1-11eb-82bd-7fa92eca4f21.png)
![image](https://user-images.githubusercontent.com/12338293/111027671-01c5da00-83f2-11eb-92aa-fcabe2fcdef7.png)
It should work for any message

**Comment by Fabian42** [comment]
Someone told me that it didn't reply on Discord, so maybe it doesn't always work. It did when I tried just now. On Telegram, it only responds to the /start, not to regular messages afterwards.

**Comment by Suppen** [comment]
It has a one minute cooldown after sending the message, in order to not spam down non-bridged chats

**Comment by Fabian42** [comment]
Actually, now that I think about it, maybe the other person sent the message while the bot was not running. That would mean that it also doesn't reply afterwards, but there were some weird issues with my bot at that time. So I guess I'll close this now until I find evidence that this is actually a problem.
