### ISSUE TITLE
3-way Bridges

### ISSUE THREAD

**Issue by Primate411** [TediCross/TediCross#188]
We have scenarios where we bridge 1 Discord to 1 Telegram group and then another Discord to the same Telegram group. Everything works well however both Discords do not see each other's messages. Telegram sees all messages. We have tried using 2 TediCross instances & bots (on both ends), 1 for the first bridge and a 2nd one for the second bridge but the 2 Discords still don't get each other's messages.  Is there any way to resolve this?

Being able to bridge 1 Telegram group to multiple Discord servers is a very desirable feature for us.

**Comment by Suppen** [comment]
No. TediCross is strictly Telegram <-> Discord. There is no way to bridge Discord -> Discord or Telegram -> Telegram.
Implementing this would require a complete rewrite of TediCross

**Comment by Primate411** [comment]
I understand this is Telegram to Discord only.  I'm checking if there is a way for 1 Telegram to Discord bridge to be seen on a second Telegram to Discord bridge to a different Discord server.  We just need the first Telegram-to-Discord bot's messages to be relayed via the second Telegram-to-Discord bot.

**Comment by Suppen** [comment]
Even going through Telegram with a  Discord -> Telegram -> Discord bridge, it is not possible to go Discord -> Discord. This is mainly due to Telegram bots' inability to see each other's messages
