### ISSUE TITLE
≥2 spaces plus linebreak become "undefined" D→T

### ISSUE THREAD

**Issue by Fabian42** [TediCross/TediCross#190]
To reproduce, send this on Discord (not as code block):
```
a  
a
```
(That is "a␣␣⏎a".)
Result on Telegram:
`aundefineda`

**Comment by Fabian42** [comment]
`---` also becomes "undefined". And
```
a
---
```
becomes `a`. I fear that something deep in the code might be seriously wrong… I hope you're not throwing the sent text into an `eval` somewhere. :D

**Comment by Suppen** [comment]
Apparently two spaces at the end of a line in markdown is a line break. https://gist.github.com/shaunlebron/746476e6e7a4d698b373

**Comment by Suppen** [comment]
and three dashes is a horizontal line

**Comment by Suppen** [comment]
Fixed in v0.10.8
