### ISSUE TITLE
[Request] Spoiler and Reaction Support 

### ISSUE THREAD

**Issue by Kallagan93** [TediCross/TediCross#205]
Telegram has a new Feature
https://telegram.org/blog/reactions-spoilers-translations

Would be cool if the bot could do that

**Comment by Suppen** [comment]
Support for spoilers t2d has been implemented on the develop branch, and will arrive in next version.

Support for spoilers d2t will require using MessageEntitites instead of HTML, which is a major change to how d2t works.
