### ISSUE TITLE
Discord to Telegram not working

### ISSUE THREAD

**Issue by bb4L** [TediCross/TediCross#240]
I had an instance running v0.10.8 that was / used to be running (but not stable)

Now i updated it to `v0.11.2` (latest that is available on dockerhub) and it only works telegram to discord but not the other way around

debug is set to true and in the logs i don't see anything... except for the heartbeat output

Is this a known issue?

Can we have `v0.11.3` also on dockerhub?

**Comment by TylerAnder** [comment]
Hello, make sure you are running with nodejs v16

Also, reset both of your telegram and discord bots' tokens, respectively, and try again.

**Comment by bb4L** [comment]
> Hello, make sure you are running with nodejs v16
> 
> Also, reset both of your telegram and discord bots' tokens, respectively, and try again.

as written above i'm using the official docker images so i guess the nodejs v16 part should be no problem

i can reset both bot tokens and check if this might resolve it, but this was a fresh setup

**Comment by TylerAnder** [comment]
Try perhaps to install it manually rather than using the docker.

Personally I used Linux server 18.04 and nodejs v16. Installed it with ```npm install --production``` command.

Try also to enable the debug from the settings file, and see if you get any specific error messages when you turn it on.

**Comment by bb4L** [comment]
> Try perhaps to install it manually rather than using the docker.
> 
> Personally I used Linux server 18.04 and nodejs v16. Installed it with `npm install --production` command.
> 
> Try also to enable the debug from the settings file, and see if you get any specific error messages when you turn it on.

i'd rather not install it locally...

debug is on but i don't get any useful information (mostly heartbeat messages) is there any further logging/debug setting to set to have verbose debugging

**Comment by TylerAnder** [comment]
Not that I know of. I had no debug error either when discord to telegram wasn't working either. It eventually only worked after I used nodejs v16 and re created the tokens. That's all I know so far

**Comment by TylerAnder** [comment]
I was on v0.10.3 before and had to switch to v0.11.3 also, for same reason.

**Comment by bb4L** [comment]
Ok turns out updating to `v0.11.3` by manually building the docker image worked / showed additional information and i got it to work in the end
