### ISSUE TITLE
Missing support for the new Telegram topics?

### ISSUE THREAD

**Issue by defi-raf** [TediCross/TediCross#243]
I set up a bridge bot for a telegram group that had topics on, producing this:

2022-12-06 00:27:38 [ERR] [REDACTED] Failed message: TelegramError: 400: Bad Request: TOPIC_DELETED
    at Telegram.callApi (/home/REDACTED/git-repos/TediCross/node_modules/telegraf/lib/core/network/client.js:264:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/REDACTED/git-repos/TediCross/dist/discord2telegram/setup.js:205:47 {
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: TOPIC_DELETED'
  },
  on: {
    method: 'sendMessage',
    payload: {
      chat_id: REDACTED,
      text: '<b>REDACTED</b>\ntest',
      parse_mode: 'HTML'
    }
  }
}

I turned the topics off and lo and behold the bridge bot then worked, so I'm guessing we need an update that allows the bridge to work with telegram topics?

**Comment by yousefmansy1** [comment]
For me It appears to be working but every message shows as a reply to the topic creator.

![Untitled](https://user-images.githubusercontent.com/36427684/207257474-e2d67759-33f3-4c1b-bedb-6d84b4421f63.png)
