### ISSUE TITLE
Bot relay option?

### ISSUE THREAD

**Issue by AmbroseSilverWolfe** [TediCross/TediCross#247]
Is there an option to relay bot messages?
I have a minecraft server with discord chat relay (for an external server, not a home server), and I want to connect that to telegram through my already established TediCross bot if possible

**Comment by Lulalaby** [comment]
Afaik bots are per default ignored, gonna look into it

**Comment by Fabian42** [comment]
Telegram bots cannot see other bots, there's nothing TeDiCross can do about it.

**Comment by Lulalaby** [comment]
If they only want a discord bot to telegram bridge for it, it should be possible. 

On that note tho, djs might ignore bots per default. It won't be something implemented directly into the source but I'm at least trying to give a solution for it.

**Comment by Fabian42** [comment]
That just works with my instance.
