### ISSUE TITLE
Telegram > Discord not working

### ISSUE THREAD

**Issue by npc-coin** [TediCross/TediCross#251]
Hello!

We've noticed a few days ago that Telegram messages have not been relayed to Discord for a while. Even trying both directions, only Discord > Telegram works atm

**Comment by NoPlagiarism** [comment]
Have you give telegram bot admin rights in chat?

**Comment by npc-coin** [comment]
Yeah I did, I run multiple bridges without a problem. Seems an issue regarding Telegram > Discord

**Comment by Lulalaby** [comment]
Did you used the correct channel ids.
Can you post related error logs please.

**Comment by svrebelo-eth** [comment]
Yes I've double checked and tried to check logs with parameter debug true but nothing was caught / shown!

**Comment by svrebelo-eth** [comment]
Sorry! replied from other account lol
I believe it stopped working from February 1st!

**Comment by svrebelo-eth** [comment]
@Lulalaby it seems to work now. I didn't make any update.

Can you clarify what has been done?

Also, are we getting a release with the major fixes / improvements?

Thanks!

**Comment by Lulalaby** [comment]
I haven't updated anything yet.

But yeah, I'm tryin my best to provide a major rework soon with stability improvements, and bug fixes.

New features will be delayed.
