### ISSUE TITLE
[Request] Hyperlink support

### ISSUE THREAD

**Issue by gappjust** [TediCross/TediCross#269]
If it's posible. can you make inline link support if sending from Telegram to Discord? It seems to be supported by Discord https://www.reddit.com/r/discordapp/comments/jy968x/you_can_now_create_hyperlinks_through_messages/

**Comment by Lulalaby** [comment]
This change was reverted by discord

**Comment by Lulalaby** [comment]
We can keep this open.

The revert is only temporary.

That said tho, it's not clear when it'll be added again.

The reason for the revert was a security issue within the new markdown and hyperlinks.

**Comment by Lulalaby** [comment]
For the future tho, please do not refer the discord subreddit.

It's mostly flooded with conspiracy theories and false info's.

For requests refer and mention the official docs.
