### ISSUE TITLE
Support for syncing pinned messages

### ISSUE THREAD

**Issue by Solomag** [TediCross/TediCross#287]
I suggest adding support for synchronizing pinned messages in TediCross. This would allow for automatic synchronization of pinned messages between Telegram and Discord, ensuring their visibility to all participants on both platforms.
I am confident that adding support for synchronizing pinned messages will greatly enhance the user experience of TediCross and streamline the synchronization process between Telegram and Discord.

**Comment by Lulalaby** [comment]
Discord has a limit of 50 pins per channel while telegram apparently has none.
This won't work out.

**Comment by Fabian42** [comment]
Why not?

**Comment by Lulalaby** [comment]
I mean. If someone is up to pr it with checks for max and unpinning older ones, feel free.

I've spoken a few days ago with a friend at discord and they won't raise the pin limit.
