### ISSUE TITLE
Crash #288

### ISSUE THREAD

**Issue by Solomag** [TediCross/TediCross#288]
**Describe the bug**
When executing the npm start command in the TediCross project, an error is encountered that сrashes the application some time after launch. The specific error message is a TypeError related to accessing undefined properties.

**To Reproduce**

Run the npm start command in the TediCross project directory.
Observe the error message displayed in the console.
Expected behavior
The application should start successfully without any errors.

**Screenshots**
![image](https://github.com/hyp3rd/telegram-discord-bridge/assets/33348398/7c6712ad-2c4c-4d51-be77-026a547067f6)

OS: Windows 11

**Additional context**
The error occurs in the middlewares.js file at line 160. It appears that the message_id property is being accessed on an undefined object, leading to the TypeError. The error message also mentions an experimental feature related to the buffer.File. This issue has been encountered while using Node.js version 18.16.0.

**Comment by Lulalaby** [comment]
cnr + chat gpt (Not recommended)
