### ISSUE TITLE
Crash #289

### ISSUE THREAD

**Issue by Solomag** [TediCross/TediCross#289]
**Describe the bug**
The bug occurs after running the npm start command for TediCross. The error is related to accessing undefined properties in the middlewares.js file.

**To Reproduce**

Run the command npm start in the TediCross directory.
Observe the console output.
Expected behavior
The application should start without any errors and function as expected.

**Screenshots**
![image](https://github.com/hyp3rd/telegram-discord-bridge/assets/33348398/b434318e-822e-4b99-b33f-24d5567af713)
Environment

Node.js version: v18.16.0

**Additional context**
The error specifically occurs in the middlewares.js file at line 259 when attempting to access the chat property of the ctx.message object. The ctx.message object seems to be undefined, leading to the error.

After few Crash #288  got that one.

**Comment by Fabian42** [comment]
Is this ChatGPT again? Please stop that.

**Comment by Lulalaby** [comment]
cnr + chat gpt (Not recommended)

**Comment by Solomag** [comment]
That is, if I just attach screenshots with an error and write "happens some time after launch", will you answer me? I made the structure myself, the bot only added where exactly the error is caused, no more.

**Comment by Lulalaby** [comment]
still cnr

**Comment by Solomag** [comment]
Is there a log file in the folder where I could find the reason for the program crash?

**Comment by Fabian42** [comment]
The AI added literally no new information. You seem to fundamentally 
misunderstand how communication works. Stop it or I'll see if I can block 
you from the repository.

**Comment by Lulalaby** [comment]
![image](https://github.com/TediCross/TediCross/assets/14029133/cb86dbac-16ee-4f9d-bfbc-a4de2fa7242a)
Ya no

**Comment by Lulalaby** [comment]
troll
