### ISSUE TITLE
Discord one way to Telegram complains files are too big in telegram

### ISSUE THREAD

**Issue by sonicer105** [TediCross/TediCross#299]
I have a one way bridge set up from Discord to Telegram, but the bot sends the message "File is too big for TediCross to handle" in the Telegram chat when a telegram message contains an attachment exceeding 25mbs. Why is it checking telegram attachments? Shouldn't telegram messages be ignored in this configuration? Is there any way to suppress this message?

**Comment by Fabian42** [comment]
What this actually means is that it can't be sent to Discord. But that's 
not even true anymore, because the default limit was raised slightly and 
some groups have higher limits. The new maintainer is already aware of this 
issue.
