### ISSUE TITLE
Display User's Server Nickname from Discord to Telegram

### ISSUE THREAD

**Issue by bmoore321** [TediCross/TediCross#30]
## Current Behavior
Discord messages sent to telegram show the Discord username.

## Expected Behavior
Discord messages sent to Telegram can display the server nickname. This is identical to [this setting](https://github.com/Suppen/TediCross/blob/d2f613b420a0ac845ace6de0218b5b38dc282a7d/example.settings.json#L7), only for messages sent from Discord to Telegram.

This is supported by the Discord API [here](https://discordapp.com/developers/docs/resources/guild#guild-member-object).

**Comment by Suppen** [comment]
Fixed by Saij
