### ISSUE TITLE
[Bug] Message formatting breaks telegram > discord

### ISSUE THREAD

**Issue by Lulalaby** [TediCross/TediCross#340]
The pull request #336 introduces a new critical bug (telegram > discord).

Message formatting cuts half of the content.

CC @Exzender (could you look into this)

![image](https://github.com/TediCross/TediCross/assets/14029133/bcd5d3f1-a1ba-4816-9a9f-956a6537fe86)

**Comment by Exzender** [comment]
Ok. I'll look

**Comment by Exzender** [comment]
Made a PR with quick-fix.
But proper fix I'm afraid not possible without full rework of entities parser with support for nested/overlapped entities.

**Comment by Lulalaby** [comment]
Yeah guessed so. Thank you.
