### ISSUE TITLE
Discord Embeds don't thumbnail content linked in them

### ISSUE THREAD

**Issue by MyrTheMoth** [TediCross/TediCross#346]
I noticed due to operations of a certain bot that uses markdown when linking images from galleries, the embeds generated as a message on the discord side don't thumbnail the content of their links, missing parity with how messages look on the telegram side message, it would be nice if at least the first link was thumbnailed, or maybe the first 5 links of an embed were posted along with it to make sure thumbnails occur? or a way to return to the pre-embed behavior if the message doesn't exceed the discord character limit.

Example:

Telegram Side
![photo_2023-08-19_20-45-11](https://github.com/TediCross/TediCross/assets/1090506/9ef55540-891c-4367-8b35-b5a58a0590c6)
Discord Side
![photo_2023-08-19_20-45-11 (2)](https://github.com/TediCross/TediCross/assets/1090506/f1fe6f81-7c7f-4593-860d-6e83c04413cf)

**Comment by Exzender** [comment]
I can't find a way to keep thumbnail of content when using embeds. The only way - is to make additional post (not embedded) with first link - so Discord will make thumbnail for it. But that would be 2 posts for 1 telegram post. 
So, more correct way would be disabling embeds at all - set 'useEmbeds' to 'never'.
But I should also note that the preview is now disabled for regular messages with links as well (it was a mess when some message contains many links)

I propose the following solution:
1. Enable preview for the first link only in the regular message (when useEmbeds set to 'never'). So if the user wants to see link previews - he should disable embeds in bot config file.
2. Work of embeds stays the same. No preview thumbnails.
3. Comment: markdown link format []() works pretty good in regular messages, except the one, when link caption = link url (when text link auto formatted as link by Telegram).  So in this solution I propose to replace full URL in link caption with word 'link' - in that case discord displays link correctly. 

If you consider it as acceptable I will make PR with these changes.

**Comment by MyrTheMoth** [comment]
I think previewing the first link only is the best approach, since that's how Telegram does it and it'd be best to keep parity with how messages behave both ways at least in that regard~

I agree with this solution, I love how embeds do their thing, just wish they could at least scape and display the first link, the first link for those is a direct link to an image, I wonder if an image URL could be passed as a thumbnail for an embed, if it was possible, wouldn't it be fine to check if the first link in an embed is an image url and make a condition to add it to the embed as such?

**Comment by Lulalaby** [comment]
It would be possible and I'd agree to this solution
