### ISSUE TITLE
Never write to settings file

### ISSUE THREAD

**Issue by cathrinevaage** [TediCross/TediCross#38]
The file `settings.json` should never be written to, as this belongs to the users domain.
Error out and/or warn user if it has shortcomings.

This is also troublesome when setting up the app, or doing development, because fatal errors in the startup phase will case the async write operation to cancel, and leave the file blank.

**Comment by Suppen** [comment]
As of commit 5ee6c54825f036269ee5dd5fc7d2ceb6d6e7f896 it uses `writeFileSync`, no longer leaving the file blank if an error happens during startup

**Comment by Suppen** [comment]
I'm planning to make editing the settings file manually unnecessary, instead having the bot controlled through either Discord or Telegram. This means the file goes out of the user's domain, making this issue irrelevant

**Comment by Suppen** [comment]
The application no longer crashes if the settings file is not writeable. It will attempt to write to it if there are changes, and will issue a warning if the file is unwriteable. If so, a new settings file with the changes will appear in the OS's temporary directory
