### ISSUE TITLE
Basic reaction support

### ISSUE THREAD

**Issue by mszaro** [TediCross/TediCross#385]
Is it possible to implement basic reaction support over the wire? For example, if I react with a 👍🏻 to a message on one side of the bridge, then the bot could react to the message on that side with the same emoji.

Obviously, features like custom emojis, reaction counts or reaction attributions to a user will not be possible; however, perhaps the bot can react across the wire in response to basic, Unicode standard emojis.

**Comment by Lulalaby** [comment]
Since the implementation for reactions differ from each platform, we won't be doing this. We might accept pull requests for such a feature tho, depending on how stable the implementation would be.

**Comment by mszaro** [comment]
Understandable. It looks pretty non trivial which is why I was suggesting just a few basic inroads.
