### ISSUE TITLE
message can' delete from telegram

### ISSUE THREAD

**Issue by ocean-dtravel** [TediCross/TediCross#431]
Hello team,
I can't delete my message from telegram group. 
1 . Send a message from Telegram  - bridged to Discord successfully
2. Delete message on Telegram - message only deleted on telegram not deleted on Discord

**Comment by Lulalaby** [comment]
That's a telegram limitation and should be noted somewhere I believe.
To delete from telegram => discord side, edit a message to `.`

**Comment by ocean-dtravel** [comment]
Thank you very much for your answer
