### ISSUE TITLE
Support discord emojis

### ISSUE THREAD

**Issue by molteber** [TediCross/TediCross#44]
https://discordapp.com/developers/docs/resources/emoji

Should consider supporting discord emojis as they turn out to be something like this: <:wixSanic:291816228945788928>

Standalone emojis could be sent as a compact image, while for complete messages with emojis, could be changed to maybe an url to the actual emoji?

**Comment by trgwii** [comment]
You could markdown it too for message + emoji combos, possibly resulting in something like:

"Hello, emoji is [Emoji:wixSanic](https://cdn.discordapp.com/emojis/291816228945788928.png) between these words."

**Comment by Suppen** [comment]
I don't think this will be practical to implement, and nobody has asked for it. Marking as wontfix and closing
