### ISSUE TITLE
"This is an instance of a TediCross bot" Spam, regression of #144

### ISSUE THREAD

**Issue by sonicer105** [TediCross/TediCross#469]
Getting the "This is an instance of a TediCross bot" message being sent in non-birdged channels in the discord about every minute when anyone says anything in them. Possible regression of #144 using the latest tedicross/tedicross docker image. 

EDIT: Config file: https://gist.github.com/sonicer105/31071e7012cf8a3d3e1d4ab9682d6d4c

**Comment by Lulalaby** [comment]
you have to set the supress confignor remobe the bot from the channels it shouldnt bridge
