### ISSUE TITLE
Telegram -> Discord delete doesn't work

### ISSUE THREAD

**Issue by gades** [TediCross/TediCross#486]
`  - name: En Chat
    direction: both
    telegram:
      chatId: [chat_id]
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: true
      crossDeleteOnDiscord: true
    discord:
      channelId: [channel_id]
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: true
      crossDeleteOnTelegram: true
      disableWebPreviewOnTelegram: true
      useEmbeds: auto`
      
      1) Type message in telegram
      2) Your message in Discord will appear
      3) Delete message in telegram
      4) Telegram message in Discord will not deleted
      
      Discord bot have admin rights in the channel
      
      tedicross/tedicross                                             latest       e32267248daf   2 months ago   738MB

**Comment by Fabian42** [comment]
https://github.com/TediCross/TediCross?tab=readme-ov-file#deleting-a-message-in-telegram-does-not-delete-it-in-discord
