### ISSUE TITLE
Unhandled Promise Rejection Warning

### ISSUE THREAD

**Issue by Kaldrogh** [TediCross/TediCross#62]
```
Request error: { Error: connect ETIMEDOUT 149.154.167.220:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '149.154.167.220',
  port: 443 }
(node:31636) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 149.154.167.220:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
(node:31636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Request error: { Error: connect ETIMEDOUT 149.154.167.220:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '149.154.167.220',
  port: 443 }
2018-04-02 21:08:27 [ERR]       Failed at getting the Telegram bot's me-object: { Error: connect ETIMEDOUT 149.154.167.220:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '149.154.167.220',
  port: 443 }
(node:31636) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 149.154.167.220:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
(node:31636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```
My bot was working like a charm for a while, but since last friday, it can't connect to the telegram channel and your program throws this error message.

Whats's going on ? Any idea ?

Thanks.

**Comment by Suppen** [comment]
Telegram did have issues a few days ago, making bots behave strangely. Based on your error messages, that appears to still be the case for you. It's unable to connect to Telegram's servers for some reason.

This persists even after restarting the bot?

**Comment by Suppen** [comment]
Could you try connecting to https://api.telegram.org/bot<TOKEN>/getMe (with your actual bot token instead of <TOKEN>)? What happens?

**Comment by Kaldrogh** [comment]
Yes, it keeps throwing me this message, and sometimes it starts working again after letting your program trying to reconnect for two or three hours, but it's very random.

**Comment by Kaldrogh** [comment]
I can't access to the url you've given me, my browser says that this website is unreachable.

**Comment by Kaldrogh** [comment]
![image](https://user-images.githubusercontent.com/22390211/38212023-a4e5127c-36bc-11e8-8a0a-dfd3237831e3.png)

**Comment by Suppen** [comment]
If you can't connect to that URL, the problem is either on your end or with Telegram. The bot uses that exact URL to get information about itself.

 Could you try from a different computer? Ideally also a different network, like at a friend's place or the library or something. Even more ideally somewhere else in the world, to get it to connect to a different Telegram server

The bot appears to be working as intended, communicating with Telegram's servers when it can

**Comment by Kaldrogh** [comment]
Yes, i've already tried from an other network in a different city yesterday on my laptop, and it appeared to work. However, i've got this exact error message at least two or three times during my test, so it was working, but not flawlessly.

I'va also tried to take control of my main machine which is located in a different city and i couldn't make it work at all.

The two city are 400 kms away, it's not that far and i think that the datas are serving from the same telegram server.

Unfortunately, i cannot make the same test today since i'm back to my city. But i'll try to go in a coffee shop or somewhere outside my house to try it again.

Anyway, thank you very much for your help.

**Comment by Kaldrogh** [comment]
So, i have migrated on Google Cloud Plateform, everything is working fine, but i have this error message : 

`[ERR]	Couldn't fetch Telegram messages. Reason: Error: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running`

Do you have any idea about this error ?

Thanks.

**Comment by Suppen** [comment]
https://github.com/TediCross/TediCross#tedicross-spams-errors-in-the-console-saying-terminated-by-other-long-poll-or-web-hook

**Comment by Kaldrogh** [comment]
The problem was totally different to be honest, there was a problem in the conf file of the Google cloud app, it was allowed to spawn multiple instances of your app to distribute the content, which has caused this conflict.

Thank you for your help.
