### ISSUE TITLE
Feature suggestion: Inline preview for replied messages on Discord

### ISSUE THREAD

**Issue by Fabian42** [TediCross/TediCross#66]
Telegram shows a preview of the message I'm answering and since that's a great thing, so maybe in Discord the bot could put a quote at the beginning of the message whenever I answer another message, maybe cropped to 100 characters or so?

**Comment by Suppen** [comment]
Good idea. Will see what can be done this weekend

**Comment by Suppen** [comment]
Implemented in commit 42d4812322c8d1a998911d9ddf2fbdccf6ae8f54
