### ISSUE TITLE
Feature request: Typing indicator

### ISSUE THREAD

**Issue by Fabian42** [TediCross/TediCross#67]
I don't know if it's possible to make a bot pretend to be typing, but if it is, it would be great to see "XYZbot is typing" whenever someone on the other side types.

**Comment by Suppen** [comment]
That reference in the commit was for issue #66, not this one...

**Comment by Suppen** [comment]
Discord informs the bot that someone is typing, so it can theoretically be implemented Discord->Telegram. The other way is not possible, as far as I can tell

**Comment by aleksandervines** [comment]
so this doesn't hold for groups? 
https://stackoverflow.com/questions/33599031/whats-the-telegram-api-method-to-get-user-is-typing-info-on-a-conversation

**Comment by trgwii** [comment]
> https://stackoverflow.com/questions/33599031/whats-the-telegram-api-method-to-get-user-is-typing-info-on-a-conversation

This is for the Telegram Client API, NOT the Bot API. Bots can't use these methods.

**Comment by aleksandervines** [comment]
I see. A bit weird to leave it out, but also understandable why.
