### ISSUE TITLE
Long messages aren't sent from Telegram to Discord

### ISSUE THREAD

**Issue by Fabian42** [TediCross/TediCross#68]
Telegram's character limit is above the one of Discord. So a user can send a message and expect it to arrive, but it never does. The console prints out an error, but the user in the Telegram chat doesn't see that.
Very long messages are automatically split up by Telegram, but the resulting messages are too long for Discord, too.

The best solution would probably be to split up the messages on the Discord end.

**Comment by Suppen** [comment]
Some quick testing shows that Telegram has a char limit (or is it byte limit?) of 4096 per message, while Discord has 2000 characters (it claims. Could still be bytes)

**Comment by Suppen** [comment]
Telegram's 4096 limit is in characters. Sending 4096 multibyte characters like '€' works fine. Adding one makes a second message.

Discord's limit is also in characters. Sending it 2000 (minus length of the sender name) '€' works fine. Adding one makes the bot complain

**Comment by Suppen** [comment]
A side effect of the fix caused the name to be sent in its own message

**Comment by Suppen** [comment]
A negative side effect of this is that for message editing purposes, only the last of the chunks are considered. I don't think this is much of a problem, though

**Comment by Fabian42** [comment]
You mean that when I edit a long message, only edits of the last part of it will be transferred to Discord? That's a bug. Could the bot maybe remember which Discord messages belong to the Telegram message and check all of them for differences to the Telegram message?

**Comment by Fabian42** [comment]
Also: What happens if I send "A\n\n\n...(repeat 3000 times)...\n\n\nB" in Telegram? Would the newlines at the end of the first and beginning of the second message be removed?
