### ISSUE TITLE
Discord channel names don't get linked

### ISSUE THREAD

**Issue by Fabian42** [TediCross/TediCross#74]
When there's a channel #test on the Discord server, typing #test in Discord adds a link to that channel. But sending #test in Telegram and having the bot relay it to Discord doesn't add that link. That's a bit unintuitive.

**Comment by Fabian42** [comment]
We tested some more and I might be able to generate an endless stream of bug reports now. :D

**Comment by Suppen** [comment]
I'm not sure this is even possible to fix. There's no special handling of #tags sent from Telegram, and Discord's [send](https://discord.js.org/#/docs/main/stable/class/TextChannel?scrollTo=send) takes just a string. I have no way of telling Discord that this is a channel name

**Comment by Fabian42** [comment]
How can it then look different on Discord when the bot sends it than when a
user sends it? Where is that information saved that it should look
different?

**Comment by Suppen** [comment]
It might be that bots simply aren't allowed to link to channels. I tried making a tiny script which does nothing but send the string "#t1" (which is a channel in my test server), and Discord just treated it as normal text

**Comment by Suppen** [comment]
This is a test: #general

**Comment by Suppen** [comment]
All issues and issue comments to this repo are forwarded to a hidden channel on the Discord side of the TediCross support server through a webhook. It also does not treat #tags any different from normal text

![bilde](https://user-images.githubusercontent.com/12338293/41586392-f409e508-73ac-11e8-9975-03cde27ef57c.png)

**Comment by Fabian42** [comment]
Some people sent me something, no idea how they did it, that looked like
<#381490427255324672>
on Discord, but came out as
#general
on Telegram for me. I'm still trying to find out how they did it, maybe it
works similarly the other way around.

**Comment by Suppen** [comment]
That's helpful. User mentions work much the same way. TediCross contains code which translates @mentions from Telegram to something like <@8752309454623> before sending it to Discord. The same might work with channels

**Comment by Fabian42** [comment]
It worked!
[image: image.png]
So the bot just has to check if the message contains a tag, then check if
that tag corresponds to a channel name on Discord, then replace the tag
with less than, hash character, the channel ID, greater than.

**Comment by Fabian42** [comment]
But I can't get it to work for mentioning users.

**Comment by Fabian42** [comment]
<@12345> becomes blue and looks clickable, but clicking on it does nothing.
That seems like a Discord bug.

**Comment by Suppen** [comment]
Probably because there is no user with ID 12345. <@83182919866122240> makes a mention of me

**Comment by Fabian42** [comment]
Where did you get that ID from? It's not the one that appears when you tag someone in Discord. That would be <@8264> for me, but it doesn't work.

**Comment by Suppen** [comment]
From my `data/discord_users.json` file. It contains the ID of everyone who has been in a bridged server

**Comment by Suppen** [comment]
Fixed. It will, however, not work when doing it as captions to files. I'll make a separate issue on that

**Comment by Fabian42** [comment]
Does pinging "@everyone" and "@here" also work?

**Comment by Suppen** [comment]
Yes, unless disabled on the Discord server
