### ISSUE TITLE
Files over 8MB are not sent T->D

### ISSUE THREAD

**Issue by Fabian42** [TediCross/TediCross#76]
Discord's file size limit is 8MB, so of course files between 8MB and 1.5GB are not sent from Telegram to Discord, but appear like they should.

Since I don't think there's any way to fix that, the bot should probably just respond on Telegram with a message saying that it can't work.

**Comment by evansan** [comment]
You mean should respond on Discord?

**Comment by Fabian42** [comment]
No, since you already get an error message if you try to send messages over 8MB on Discord. By Discord itself. But if it goes from Telegram through the bot to Discord, it's just silently discarded.

**Comment by Suppen** [comment]
Fixed in version 0.9.13
