### ISSUE TITLE
Are messages deleted with the bridge?

### ISSUE THREAD

**Issue by stevemulligan** [TediCross/TediCross#77]
If I delete a message on Discord is it possible to have the message deleted on Telegram (and also in the other direction?)

**Comment by Suppen** [comment]
Unfortunately, no. Telegram bots are completely unable to detect when a message has been deleted, and TediCross can therefore not tell Discord to delete the corresponding message there. I have mentioned it to the Telegram team, and they said "Guess it's just a missing feature :)", so it will hopefully be implemented soon. I will make the bot able to delete messages the moment I can do it.

Discord bots, on the other hand, ARE able to detect deleted messages. However, I don't want to introduce asymmetric deletion, as that will create a flood of questions and issues

**Comment by stevemulligan** [comment]
thanks for the reply, looking forward to seeing it someday.
