### ISSUE TITLE
Make the bot delete messages

### ISSUE THREAD

**Issue by Suppen** [TediCross/TediCross#78]
*This is a frequently requested feature of TediCross which unfortunately cannot currently be implemented*

When a message is deleted in Telegram, the corresponding message in Discord should also be deleted, and vice versa.

Unfortunately, Telegram bots are completely unable to detect when a message has been deleted. This It is therefore impossible for the bot to implement this in the T2D direction. I have mentioned this to the Telegram Bot Support, and they replied with "Guess it's just a missing feature :)". Hopefully they make bots able to detect deleted messages soon. I will update the bot as soon as Telegram makes the change

**Comment by Suppen** [comment]
This is now implemented D2T. The other way is still not possible

**Comment by rraallvv** [comment]
I haven't tried `getUpdates` in the Telegram API but it seems one could poll the latest N messages, and check those with the corresponding messages from the Discord side to see which ones were deleted.

**Comment by Suppen** [comment]
That will not work. `getUpdates` is already the way TediCross gets messages from Telegram. You can test yourself:

* Make a new bot by taling to @botfather in Telegram
* Start a conversation with the bot
* Send it a message
* Go to https://api.telegram.org/bot706918798:AAGWa_URS56JZqE_ANZGa3uSmGTYMWlWCSM/getUpdates and you will see your message. Switch the token in the URL with the token for your bot
* Delete the message you sent the bot in Telegram. It will even say "This will delete [the message] just for you"
* Go to the URL again, or just refresh the page
* You will see the message is still there, with no indication the message has been deleted. There is also no new update saying a message has been deleted

You could also try the above in a group chat, where you can select "Delete for everyone" when deleting the message. The result will be the same

There is literally no way for Telegram bots to detect when a message has been deleted

**Comment by rraallvv** [comment]
@Suppen I see, thanks for the clarification. The Telegram side of the bridge is being heavily bombarded by spammers, I added a filter to stop most spam messages from the Telegram side, but those that still pass the Telegram filter appear in both sides of the bridge and have to be deleted by hand both from Telegram and from Discord. Maybe you have experienced or seen something similar, any suggestions on how to tackle that issue? Thanks.

**Comment by Suppen** [comment]
It is a known problem, and unfortunately not much I can do about it before Telegram decides bots can detect message deletion.

The only thing which will work is having a moderator bot on Discord too. Deleting messages in Discord will also delete the corresponding message in Telegram

**Comment by rraallvv** [comment]
@Suppen Thanks, I'll give it a try.

**Comment by Suppen** [comment]
This has been partially implemented now. If a message on Telegram is edited to a single dot, TediCross will interpret that as a delete request, and delete it and the corresponding message on Discord.

Telegram bots are still completely unable to detect when a message has been deleted, so it is still completely impossible to implement this properly
