### ISSUE TITLE
Delay the bot?

### ISSUE THREAD

**Issue by xenphiliac** [TediCross/TediCross#84]
Is it possible to delay the bot by a few seconds, so that it pulls messages every X number of seconds from Telegram or Discord?  Possibly using a sleep function?

Thank you all in advance for your help.

**Comment by trgwii** [comment]
What's the use-case? Why do you want this?

**Comment by xenphiliac** [comment]
We're using a Telegram bot that deletes foul language but the Tedicross bot picks it up too quick before it's removed by the other bot and it all goes over to Discord and vice versa.

**Comment by trgwii** [comment]
Well, deleted messages can't be detected by bots anyway, so TediCross would pick up the messages even after deletion. Consider another Discord bot to remove it on the Discord side as well?

**Comment by Suppen** [comment]
As @TRGWII said, Telegram bot's can't detect deleted messages. Even if you don't let the bot fetch the message before it is deleted, the message is still in the bot's queue. Delaying the fetching will not help
