### ISSUE TITLE
I know this is a long shot...

### ISSUE THREAD

**Issue by KittyCatGamers** [TediCross/TediCross#88]
Is there a way i can remove the branding? It's making my server look bad

**Comment by Suppen** [comment]
You mean the "This is an instance of TediCros..."? That will not appear if you have configured the bot correctly

Most of the time I have seen this problem the reason has been that people have tried using the same bot for more than just TediCross. One bot, one application. It should not be necessary to have the bot in channels/chats which are not bridged

If this happens on a Discord server which is bridged, you probably have not set/set wrong `serverId`. `channelId` tells the bot which channel to bridge, `serverId` tells the bot which server to not spam in

**Comment by KittyCatGamers** [comment]
I mean when people dm the bot

**Comment by Suppen** [comment]
That can't be removed without editing the code. Is there any reason why they would DM the bot?

**Comment by KittyCatGamers** [comment]
For commands

**Comment by KittyCatGamers** [comment]
If you tell me what file to edit i can do it

**Comment by Suppen** [comment]
What commands? The only command in TediCross is `/chatinfo`, which is not necessary to use other than for setup

**Comment by KittyCatGamers** [comment]
People see a bot they dm the bot

**Comment by KittyCatGamers** [comment]
![image](https://user-images.githubusercontent.com/26846615/46799606-8b43ce80-cd98-11e8-9152-889aeac9aaa7.png)

**Comment by Suppen** [comment]
Then isn't it good that people get informed of what the bot does, instead of not getting anything?

You can edit it out if you want to. It's in the files. But editing the code is not supported, so I won't help you. I won't stop you either, as it is open source, and you can do what you want with it

**Comment by KittyCatGamers** [comment]
What file do i edit?

**Comment by Suppen** [comment]
Editing the code is not supported, so I won't help you

**Comment by KittyCatGamers** [comment]
*right click* open with notepad++

**Comment by KittyCatGamers** [comment]
If you added it there why can't you remove it?
