### ISSUE TITLE
Discord channel names

### ISSUE THREAD

**Issue by pablobitcobar** [TediCross/TediCross#92]
Hello, is it possible to forward also discord channel name to telegram ?  for example - I have 5 channels in discord that messages i wish to forward to telegram, but without knowing from what channel messages comes , makes it in a big mess in telegram.

**Comment by trgwii** [comment]
Filtering words: only possible if you manually edit the code, the bot is not designed to be a group administration bot

Forward channel names: would probably be better to make 5 groups / channels on telegram, and bridge each discord channel to it's own telegram counterpart
