### ISSUE TITLE
Telegram messages duplicated in discord, sometimes

### ISSUE THREAD

**Issue by Myke500** [TediCross/TediCross#94]
usually happens after the chat has been silent for a period of time,

New message will duplicate as seen here
![image](https://user-images.githubusercontent.com/17334141/50050931-f4a7cc80-00bc-11e9-8979-28babac33d23.png)
But only the first time after a long pause, then is back to normal as seen here:
![image](https://user-images.githubusercontent.com/17334141/50050942-0be6ba00-00bd-11e9-8a1a-7f6f4ad77b02.png)

Unknown cause

**Comment by Myke500** [comment]
Further testing shows it may not be a long period of time, it could be random.
Had it happen several times in a row, less than 30 seconds apart.

**Comment by kaorudark** [comment]
Kill the process and restart it.
There is somewhere a Second process/bot started.

**Comment by Myke500** [comment]
It was a duplicate process as kaorudark noted
