### ISSUE TITLE
how not to show title and username on discord

### ISSUE THREAD

**Issue by cryptoleo79** [TediCross/TediCross#98]
i was advised to edit this part on setupfile for telegram to discord

			// Handle replies
			if (messageObj.reply !== null) {
				// Make a Discord embed and send it first
				const embed = new Discord.RichEmbed({
					description: `Reply to **${messageObj.reply.author}**\n${messageObj.reply.text}`
				});

				const textToSend = bridge.telegram.sendUsernames
					? `**${messageObj.from}**`
					: undefined
				;

				await channel.send(textToSend, {embed});
			}

			// Discord doesn't handle messages longer than 2000 characters. Split it up into chunks that big
			const messageText = (!bridge.telegram.sendUsernames || messageObj.reply !== null)
				? messageObj.text
				: `**${messageObj.from}**\n${messageObj.text}`

i am new to coding so i just dont know what to put in

i want to hide the chat channels name, where I forwarded the message from and also not show the user name, if possible i would like it to show like this
@here #(the channel name for Discord)

hope i can get some advice,  thank you

**Comment by Suppen** [comment]
Editing the code is not supported. You are free to do it, but you won't get help
